apiVersion: v1      
kind: Pod            
metadata:   
  name: web               
  labels:                
    pod: app 
spec:                 
  containers:       
  - name: web          
    image: ekod/web:1.0  
    imagePullPolicy: Always
  initContainers:
    - name: init-index-hmtl
      image: busybox:1.31.0
      command:
        [
          "sh",
          "-c",
          'wget -O- https://tinyurl.com/otus-k8s-intro | sh',
        ]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}       
